### PR TITLE
Correctly expand concatenated variables

### PR DESCRIPTION
**Pull request by pkubatrh**
Moved the environment variable substitution into a while loop that runs until the next character is not '$'.

Fixes: #44

### CODE REVIEW

**Comment by lcarva** [comment]
Thanks for this!

Looks like the travis build for centos failed which seems to be unrelated to your changes. I re-triggered it, but we might need to fix something there. Stay tuned.

Can we add a unit test for these changes?

**Comment by pkubatrh** [comment]
>Can we add a unit test for these changes?

Added a simple test case from #44

**Comment by lcarva** [comment]
@pkubatrh, we fixed the travis errors in https://github.com/DBuildService/dockerfile-parse/pull/46, could you please rebase your branch?

**Comment by pkubatrh** [comment]
Rebased against latest master

**Pull request merged**
