### PR TITLE
0.0.7

### PR DESCRIPTION
**Pull request by twaugh**
Prepare for 0.0.7 release.

Signed-off-by: Tim Waugh <twaugh@redhat.com>

### CODE REVIEW

**Comment by TomasTomecek** [comment]
I was thinking about publishing releases to PyPI, ideally via travis so we don't need to worry about it. What do you think?

**Comment by twaugh** [comment]
That would be great, yes. I haven't had time to look into it myself and have been publishing to PyPI manually each release.

**Comment by TomasTomecek** [comment]
Oh, and I thought it's not published on PyPI. Was probably confused by missing installation step in readme: hence PR! https://github.com/DBuildService/dockerfile-parse/pull/36

**Comment by TomasTomecek** [comment]
\o/

**Pull request merged**
